### ISSUE TITLE
注意！！！本项目的Star和Fork是购买的。

### ISSUE THREAD

**Issue by bk-vue-cec** [TinsideDesign/bk-vue-cec#1]
![](https://p.pstatp.com/origin/pgc-image/017664c5e3a447198d7becc9522af62f)

**Comment by bk-vue-cec** [comment]
现在的star和fork的5元购买已经结束。

**Comment by bk-vue-cec** [comment]
群主的QQ是915620310，欢迎与它交流。

**Comment by bk-vue-cec** [comment]
@huangkaoya

**Comment by huangkaoya** [comment]
是给忠实支持者的支持奖励，欢迎加群 877291441 参与后续活动
