### ISSUE TITLE
当页面有两个Tree时，一个开启拖拽另一个不开启 

### ISSUE THREAD

**Issue by hw952** [TinsideDesign/bk-vue-cec#2]
当页面有两个Tree时，一个开启拖拽另一个不开启 ，可以将开启拖拽Tree的节点拖拽到另一个非开启拖拽的Tree里.... 
-----
不是知道是不是这样设计的... 总感觉哪里怪怪的....

**Comment by huangkaoya** [comment]
这个是未来会完善的一个高级功能，提供跨树拖拽和默认禁止跨树拖拽。
