### ISSUE TITLE
Tree 异步加载时loading 图标靠下

### ISSUE THREAD

**Issue by hw952** [TinsideDesign/bk-vue-cec#5]
![QQ截图20210925092613](https://user-images.githubusercontent.com/32861583/134753301-afb6c738-99d4-469d-a037-0eefee9d441c.png)

**Comment by huangkaoya** [comment]
目前不影响业务功能且不影响交互观感，属于细节优化，也算一个问题，这个问题在跟进中，可能会在更晚的版本修复

**Comment by huangkaoya** [comment]
问题已经解决
